### ISSUE TITLE
Update library for dynamic SSID, PWD

### ISSUE THREAD

**Issue by jaime-mantilla** [adafruit/Adafruit_IO_Arduino#109]
Hi. any chance to dynamically assign SSID and password? Should I change location (different network) or router password I need to recompile my code.

**Comment by brentru** [comment]
As of now, Adafruit IO Arduino has no way to set the SSID/password over-the-air. We have an issue for this here: https://github.com/adafruit/Adafruit_IO_Arduino/issues/93
