### ISSUE TITLE
Missing Header File (Adafruit_IO_Client.h) and/or restructured?

### ISSUE THREAD

**Issue by slminneman** [adafruit/Adafruit_IO_Arduino#11]
- Arduino board:  Adafruit Huzzah ESP8266

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.65

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):  The "trigger" example references the header file Adafruit_IO_client.h, but no such thing appears to be present anywhere.  The structure of the file name is similar to other file names in this project, so I'm speculating that something here may be awry (or changed since the Adafruit tutorial was written).

Any thoughts on the matter?  I've also submitted a trouble report on their forums, but I'm working in parallel here, because time is of the essence.

Thanks for your thoughts/attention.

Scott

**Comment by tsalmela** [comment]
My work ended to same problem. "Adafruit_IO_Client.h: No such file or directory"
There seems to be no such file here.

Was able to find one project with that file but can't get it to work with my project: https://github.com/nicjansma/dht-logger

**Comment by toddtreece** [comment]
@slminneman please use v1.0.1 for the trigger example:

<img width="235" alt="screen shot 2017-04-11 at 9 43 12 am" src="https://cloud.githubusercontent.com/assets/360020/24912168/5b885736-1e9b-11e7-8885-882e6de7bd62.png">
