### ISSUE TITLE
Does the max csv length need to get updated as well?

### ISSUE THREAD

**Issue by blaskovicz** [adafruit/Adafruit_IO_Arduino#127]
Does the max csv length need to get updated as well, as a follow up to #119 and #126  https://github.com/adafruit/Adafruit_IO_Arduino/blob/ce83ba999056639728de655fbad49bfb4c935cfd/src/AdafruitIO_Definitions.h#L130?

_Originally posted by @blaskovicz in https://github.com/adafruit/Adafruit_IO_Arduino/issues/119#issuecomment-634052324_

**Comment by brentru** [comment]
@blaskovicz  Yes - this should be updated too. Keep in mind that the max length of CSV feeds is 4 characters larger than the max length of general IO feeds. i.e: `mosfet/feeds/photocell-one/csv` instead of `mosfet/feeds/photocell-one`

**Comment by blaskovicz** [comment]
I can add that in the same PR, thanks!
