### ISSUE TITLE
including AdafruitIO_FONA.h causes build issues

### ISSUE THREAD

**Issue by BioSLuDge** [adafruit/Adafruit_IO_Arduino#134]
- Arduino board:  Adafruit FONA feather

- Arduino IDE version:  1.8.13

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): Just try to build any Adafruit IO sketch with AdafruitIO_FONA.h, it will fail to build because the FONA library doesn't implement the _disconnect method which is required to fully implemented by the base AdafruitIO class.

I added `void _disconnect() {};` to the protected section of the FONA library and it builds and runs.  But I'm not sure if more should be in there for proper long term function or not.

**Comment by brentru** [comment]
@BioSLuDge  Hi, added a draft PR which fixes this build error and disables the GPRS module. 

https://github.com/adafruit/Adafruit_IO_Arduino/pull/135
