### ISSUE TITLE
The example code does not compile.

### ISSUE THREAD

**Issue by AntiPortalSci101** [adafruit/Adafruit_IO_Arduino#14]
- Arduino board:  Arduino uno

- Arduino IDE version: 1.6.5

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):
I compiled the adafrutio_03_multiple_feeds library, following the instructions within, and it did not compile. Please make sure all the example code itself can compile, and clearly enumerate any dependancies or external libraries the user needs to install.

**Comment by ememberus** [comment]
Similar or identical issue:
- Arduino board: HUZZAH ESP8266
- Arduino IDE: 1.8.1
- Example project: adafrutio_03_multiple_feeds
- build error message: ArduinoHttpClient.h: No such file or directory

**Comment by jwcooper** [comment]
Hi, you need to install the ArduinoHttpClient library:
https://github.com/adafruit/Adafruit_IO_Arduino#adafruit-feather-huzzah-esp8266--adafruit-huzzah-esp8266-breakout
