### ISSUE TITLE
Found some issues of AdafruitIO Arduino library 

### ISSUE THREAD

**Issue by biagiom** [adafruit/Adafruit_IO_Arduino#15]
Hi Adafruit team,

I have found some issues about the AdafruitIO Arduino library:
* the AdafruitIO_Ethernet class supports only the Ethernet2 library but I think the user should have the possibility to use the Ethernet library too, so I have added some changements to allow the user to select the appropriate library version (see [my repo](https://github.com/biagiom/Adafruit_IO_Arduino/blob/a4b91e1032e1a72df8e92fe4458de745405b5d48/src/AdafruitIO_Ethernet.h#L20)).
* the [_port variable member](https://github.com/adafruit/Adafruit_IO_Arduino/blob/86733a8a6c0107d897d7fc4c37197f24e9e3e10d/src/AdafruitIO_Ethernet.h#L54) of AdafruitIO_Ethernet class should be renamed in _mqtt_port in order to use the 1883 port instead of the default port 8883 (MQTT over TLS) because the Ethernet and Ethernet2 libraries does not support secure connection over SSL/TLS (see also [line 34](https://github.com/adafruit/Adafruit_IO_Arduino/blob/86733a8a6c0107d897d7fc4c37197f24e9e3e10d/src/AdafruitIO_Ethernet.h#L34)).
* ~~the adafruitio_10_dashboard_creation sketch does not work with the current library version:
  I found that passing the key using the X-AIO-Key accept header does not work in fact the only way to
  send http GET request was to add the key as a a query parameter but this is not secure.~~
  ~~Furthermore I only managed to send JSON formatted data (it seems that the _application/x-www-form-urlencoded_ mime type is not supported).~~
  For more info see [my post](https://forums.adafruit.com/viewtopic.php?f=56&t=122537) on the AdafruitIO Forum and [my changements to the library](https://github.com/biagiom/Adafruit_IO_Arduino/tree/dev).
With my changements that you can find in in the dev branch of my fork of Adafruit_IO_Arduino, the
adafruitio_10_dashboard_creation sketch works with ESP8266 Nodemcu and Feather HUZZAH but it still does not work with Arduino 101 + Ethernet Shield (the other examples works with Arduino 101 + Ethernet Shield).

Useful info:
- Tests made with the following boards:
  * Adafruit Feather HUZZAH ESP8266
  * Nodemcu ESP8266
  * Arduino 101 + Ethernet Shield

- Arduino IDE version: 1.8.3

Best regards.

**Comment by biagiom** [comment]
Update:
I have tested again the the adafruitio_10_dashboard_creation sketch and I confirm that application/x-www-form-urlencoded mime type works.

**Comment by abachman** [comment]
Thanks for the issue + branch! I'll take a look at your changes and see what we can incorporate.

> passing the key using the X-AIO-Key accept header does not work in fact the only way to send http GET request was to add the key as a a query parameter but this is not secure.

Unfortunately, when we use `http://` or `mqtt://` instead of the secure formats, the key is insecure regardless of where we send it, header or query. I expect our eventual "solution" to that problem to be per-device, limited-access tokens. There's isn't much else we can do except wait for hardware to catch up with SSL / TLS.
