### ISSUE TITLE
Feature request: mqtt for aruino portenta mbed series

### ISSUE THREAD

**Issue by hpssjellis** [adafruit/Adafruit_IO_Arduino#150]
Feature request: mqtt for aruino portenta mbed series.

The Adafruit.io dashboard works really well on the Helium LoRaWan network with the LoRa Portenta Vision shields, but  does not presently work with WiFi or Ethernet. Hopefully the Arduino MBEd boards can be included with s basic example.

**Comment by ladyada** [comment]
hiya this would be best to ask arduino to add support for mqtt since they have a library they wrote!

**Comment by hpssjellis** [comment]
@ladyada Thanks for the reply. I now have found the arduino library '''#include <ArduinoMqttClient.h>'''  and it seems to basically work. The Adafruit MQTT dashboard is very good. You people do very good work. Thank you for doing that and making it public. I need to promote Adafruit more. Look for my tweets from @rocksetta.

**Comment by ladyada** [comment]
nice!
