### ISSUE TITLE
Group feeds not working?

### ISSUE THREAD

**Issue by j15e** [adafruit/Adafruit_IO_Arduino#16]
Board : ESP8266 Feather Huzzah 12S
Sketches : https://gist.github.com/j15e/2a91c09f8e4a0a12a187e32fee770615

The `group.c` is not receiving any message whereas `single-feed.c` works as expected. I also have try to set / publish a value and it doesn't work via the group class either. 

I do have the feed `pump` setup in the `garden` group (I think?) ;

<img width="658" alt="capture d ecran 2017-09-27 a 22 51 06" src="https://user-images.githubusercontent.com/143380/30947212-66f77c12-a3d6-11e7-9ce1-ffb37c26b39c.png">

**Comment by sommersoft** [comment]
I know this is a month old, and I'm surprised that there hasn't been a response yet. Everything looks like you've set it up correctly. 

Are you adding data on the AIO website while your code is running, or are you relying on the group.c publish? I have noticed that the IO library only responds to data updates that come from dashboard blocks like the toggle switch, slider, etc. It doesn't receive (or parse actually, according to the debug from MQTT.cpp) data from the "Add Data" in the feed itself.

It does receive published data that is published from the IO library (watch out for circular references).

I did notice that when you're publishing in group.c, you seem to have missed a step:

````
garden->set("pump", "hello world");
garden->save();
````

You need the **`save()`** to push the data.

**Comment by sommersoft** [comment]
To help explain my above comment on the "parse" error, here is the Adafruit_MQTT.cpp debug information from using two different update procedures on the AIO website.

Using a slider bar to update the balance feed:
```
Read data:		0 [0x30], 
Packet Type:		0 [0x30], 
Read data:		' [0x27], 
Packet Length:	39
Read data:		  [0x00],   [0x19], s [0x73], o [0x6F], m [0x6D], m [0x6D], e [0x65], r [0x72], 
	s [0x73], o [0x6F], f [0x66], t [0x74], / [0x2F], g [0x67], / [0x2F], d [0x64], 
	r [0x72], u [0x75], m [0x6D], t [0x74], i [0x69], m [0x6D], e [0x65], / [0x2F], 
	c [0x63], s [0x73], v [0x76], b [0x62], a [0x61], l [0x6C], a [0x61], n [0x6E], 
	c [0x63], e [0x65], , [0x2C], - [0x2D], 3 [0x33], 0 [0x30],   [0x0A], 
Packet len: 41
	0 [0x30], ' [0x27],   [0x00],   [0x19], s [0x73], o [0x6F], m [0x6D], m [0x6D], 
	e [0x65], r [0x72], s [0x73], o [0x6F], f [0x66], t [0x74], / [0x2F], g [0x67], 
	/ [0x2F], d [0x64], r [0x72], u [0x75], m [0x6D], t [0x74], i [0x69], m [0x6D], 
	e [0x65], / [0x2F], c [0x63], s [0x73], v [0x76], b [0x62], a [0x61], l [0x6C], 
	a [0x61], n [0x6E], c [0x63], e [0x65], , [0x2C], - [0x2D], 3 [0x33], 0 [0x30], 
	  [0x0A], 
Looking for subscription len 25
Found sub #0
Data len: 12
Data: balance,-30

received drumtime.balance: -30
```
And this is one is using the "Add Data" function on the feed itself:
```
Read data:		0 [0x30], 
Packet Type:		0 [0x30], 
Read data:		  [0x1B], 
Packet Length:	27
Read data:		  [0x00],   [0x19], s [0x73], o [0x6F], m [0x6D], m [0x6D], e [0x65], r [0x72], 
	s [0x73], o [0x6F], f [0x66], t [0x74], / [0x2F], g [0x67], / [0x2F], d [0x64], 
	r [0x72], u [0x75], m [0x6D], t [0x74], i [0x69], m [0x6D], e [0x65], / [0x2F], 
	c [0x63], s [0x73], v [0x76], 
Packet len: 29
	0 [0x30],   [0x1B],   [0x00],   [0x19], s [0x73], o [0x6F], m [0x6D], m [0x6D], 
	e [0x65], r [0x72], s [0x73], o [0x6F], f [0x66], t [0x74], / [0x2F], g [0x67], 
	/ [0x2F], d [0x64], r [0x72], u [0x75], m [0x6D], t [0x74], i [0x69], m [0x6D], 
	e [0x65], / [0x2F], c [0x63], s [0x73], v [0x76], 
Looking for subscription len 25
Found sub #0
Data len: 0
Data: 
```

**Comment by sommersoft** [comment]
Seems that today's update on feed & group topics has fixed this particular problem (at least for what I posted). 

Here is the new result when using "Add Data" on the AIO website:
```
Read data:		0 [0x30], 
Packet Type:		0 [0x30], 
Read data:		& [0x26], 
Packet Length:	38
Read data:		  [0x00],   [0x19], s [0x73], o [0x6F], m [0x6D], m [0x6D], e [0x65], r [0x72], 
	s [0x73], o [0x6F], f [0x66], t [0x74], / [0x2F], g [0x67], / [0x2F], d [0x64], 
	r [0x72], u [0x75], m [0x6D], t [0x74], i [0x69], m [0x6D], e [0x65], / [0x2F], 
	c [0x63], s [0x73], v [0x76], b [0x62], a [0x61], l [0x6C], a [0x61], n [0x6E], 
	c [0x63], e [0x65], , [0x2C], 1 [0x31], 2 [0x32],   [0x0A], 
Packet len: 40
	0 [0x30], & [0x26],   [0x00],   [0x19], s [0x73], o [0x6F], m [0x6D], m [0x6D], 
	e [0x65], r [0x72], s [0x73], o [0x6F], f [0x66], t [0x74], / [0x2F], g [0x67], 
	/ [0x2F], d [0x64], r [0x72], u [0x75], m [0x6D], t [0x74], i [0x69], m [0x6D], 
	e [0x65], / [0x2F], c [0x63], s [0x73], v [0x76], b [0x62], a [0x61], l [0x6C], 
	a [0x61], n [0x6E], c [0x63], e [0x65], , [0x2C], 1 [0x31], 2 [0x32],   [0x0A], 
	
Looking for subscription len 25
Found sub #0
Data len: 11
Data: balance,12

received drumtime.balance: 12
```

See here for the changelog: [Groups, Feeds, and Proper MQTT Topics](https://io.adafruit.com/blog/notebook/2017/11/02/groups-feeds-and-fixing-mqtt-topics/)

j15e, can you confirm if your issue is resolved?

**Comment by j15e** [comment]
Hi! Thanks for looking into my issue! I moved to using non-grouped feeds for now but I am glad to hear this is fixed!

**Comment by eighthree** [comment]
Using an ESP32 Feather I too was getting issues using group feeds and reverted back to singles.

Here's what I've got:
`Decoding 9 results
0x400d2b18: AdafruitIO_Group::call(AdafruitIO_Data*) at C:\Users\eight\Documents\Arduino\libraries\Adafruit_IO_Arduino\src/AdafruitIO_Group.cpp line 320
0x400d2b18: AdafruitIO_Group::call(AdafruitIO_Data*) at C:\Users\eight\Documents\Arduino\libraries\Adafruit_IO_Arduino\src/AdafruitIO_Group.cpp line 320
0x400d2bbd: AdafruitIO_Group::subCallback(char*, unsigned short) at C:\Users\eight\Documents\Arduino\libraries\Adafruit_IO_Arduino\src/AdafruitIO_Group.cpp line 320
0x400d3148: Adafruit_MQTT::processPackets(short) at C:\Users\eight\Documents\Arduino\libraries\Adafruit_MQTT_Library/Adafruit_MQTT.cpp line 827
0x400d279e: AdafruitIO::run(unsigned short) at C:\Users\eight\Documents\Arduino\libraries\Adafruit_IO_Arduino\src/AdafruitIO.cpp line 164
0x400d2374: loop() at C:\Users\eight\Documents\Arduino\sketch_jan13a/sketch_jan13a.ino line 84
0x4012cfcc: loopTask(void*) at C:\Users\eight\Documents\Arduino\hardware\espressif\esp32\cores\esp32/main.cpp line 18 (discriminator 1)`

Line 827 of Adafruit_MQTT.cpp
`
void Adafruit_MQTT_Subscribe::setCallback(SubscribeCallbackDoubleType cb) {
  callback_double = cb; // line 827
}
`

Line 320 of AdafruitIO_Group.cpp
`
bool AdafruitIO_Group::create()
{
   /* code omitted for discord*/
} // <-- Line 320
`

Line 164 of AdafruitIO.cpp:
`  _mqtt->processPackets(_packetread_timeout); `

Line 84 of Sketch is `io.run();`

**Comment by brentru** [comment]
This has been patched. Closing...
