### ISSUE TITLE
Memory leak in save() ?

### ISSUE THREAD

**Issue by cahenesy** [adafruit/Adafruit_IO_Arduino#21]
- Arduino board:  Adafruit Huzzah Feather (ESP8266)
- Arduino IDE version (found in Arduino -> About Arduino menu): 1.8.5
- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 

I have found that when I create a feed (example):
AdafruitIO_Feed *systemBatteryVoltageFeed = io.feed("system-battery-voltage");

And then in my loop() I save a value to the feed (example):
systemBatteryVoltageFeed->save(systemBatteryVoltage);

After a while, the board will crash such that not even hitting the reset button helps and I have to disconnect power to reset.  After googling around a bit, I began to suspect a memory leak, so I added code to check heap size on each iteration of the "take measurements and upload results" of the loop:

extern "C" {
#include "user_interface.h"
}
uint32_t freeMem = system_get_free_heap_size();

And I find that, indeed, I am losing memory with each call to systemBatteryVoltageFeed->save

**Log output w/ call to save() in place:**
.........
Adafruit IO connected.
Measuring system battery voltage..
Beginning Adafruit IO Updates...
Updates Completed!
Free memory: 17472
Measuring system battery voltage..
Beginning Adafruit IO Updates...
Updates Completed!
Free memory: 17408
Measuring system battery voltage..
Beginning Adafruit IO Updates...
Updates Completed!
Free memory: 17344
Measuring system battery voltage..
Beginning Adafruit IO Updates...
Updates Completed!
Free memory: 17280
Measuring system battery voltage..
Beginning Adafruit IO Updates...
Updates Completed!
Free memory: 17216
Measuring system battery voltage..
Beginning Adafruit IO Updates...
Updates Completed!
Free memory: 17152
Measuring system battery voltage..
Beginning Adafruit IO Updates...
Updates Completed!
Free memory: 17088
Measuring system battery voltage..
Beginning Adafruit IO Updates...
Updates Completed!
Free memory: 17024
Measuring system battery voltage..

**Log output with call to save() commented out:**
.....
Adafruit IO connected.
Measuring system battery voltage..
Free memory: 18048
Measuring system battery voltage..
Free memory: 18048
Measuring system battery voltage..
Free memory: 18048
Measuring system battery voltage..
Free memory: 18048
Measuring system battery voltage..
Free memory: 18048

**Comment by rdmrocha** [comment]
This explains the leak I'm also seeing on my implementation. Managed to fix it on my side. Will create a pull request ;)

**Comment by cahenesy** [comment]
Your patch fixed it for me.  Thanks!
