### ISSUE TITLE
Adafruit IO Arduino Library Dependents – Installation Problems

### ISSUE THREAD

**Issue by Starkshub** [adafruit/Adafruit_IO_Arduino#46]
Adafruit IO Arduino Library Dependents – Installation Problems

Hello GIT Members...
Notes:
Board - Adafruit Feather 32
Sketch - Trigger
Issue - Library Dependents (install)

I am trying to use the Trigger Sketch (on the ESP32) that was written for the Huzzah 8266 Board. Some of the commands do not work with ESP32 Board and I am changing them to the commands that work with the ESP32.

When I change the include library "Adafruit_IO_Client.h" that returns an error from that library to the downloaded Adafruit IO library that I updated from GIT (on this page) I am getting errors with all of the following dependents that populate the sketch:
#include <AdafruitIO.h>
#include <AdafruitIO_Dashboard.h>
#include <AdafruitIO_Data.h>
#include <AdafruitIO_Definitions.h>
#include <AdafruitIO_Ethernet.h>
#include <AdafruitIO_Feed.h>
#include <AdafruitIO_FONA.h>
#include <AdafruitIO_Group.h>
#include <AdafruitIO_MQTT.h>
#include <AdafruitIO_Time.h>
#include <AdafruitIO_WiFi.h>

I am then going into the Library Manager and searching each line error (example - the first line - #include <AdafruitIO.h>) then installing each one separately . I would think that when I downloaded, and unzipped the "Adafruit IO Arduino", the dependents would also be installed.

Am I doing something incorrectly?
Do I have to install each dependent individually in the Library Manager as I am now doing?

Additional Note:
After I go into the Library Manager, search and install each dependent listed above, the only one that keeps coming back with an error is <AdafruitIO_FONA.h>.

Any input is appreciated.

Current Error Code after all above dependents are independently installed:
C:\Users\CAB\Documents\Arduino\libraries\Adafruit_IO_Arduino-master\src/AdafruitIO_FONA.h:16:28: fatal error: SoftwareSerial.h: No such file or directory

**Comment by Starkshub** [comment]
Additional Note:

I did use the Library Manager (Add Zip Library) when I added this Adafruit_IO_Arduino Library to my IDE.

**Comment by brentru** [comment]
Hi @Starkshub - you mentioned you were using the trigger sketch. Which sketch within the examples directory (https://github.com/adafruit/Adafruit_IO_Arduino/tree/master/examples) would that be? 

Could you try [installing from the Arduino Library manager](https://learn.adafruit.com/welcome-to-adafruit-io/libraries#installation), instead of installing from git?

**Comment by Starkshub** [comment]
Hi Brentru... 

Thank you for your help.

1) The Trigger Sketch is based on an example from an Adafruit Learning Module:

https://learn.adafruit.com/using-ifttt-with-adafruit-io/arduino-code-1

2) The actual Sketch is based on the 8266 board example found at the following GIT Link:

https://github.com/adafruit/adafruit-io-basics

3) I did check my Library Manager and updated the Adafruit IO Arduino Library to version 2.7.8

the (#include <AdafruitIO_FONA.h>) still returns the same error.

I did download the library from GIT (this page) and used the Library Manager (include ZIP) from the Arduino IDE. Should I have done this a different way?

As I mentioned, I am advancing my skills from the UNO to the 32 board. I am using the 8266 Trigger Sketch as a starting point and updating the code line by line to work with the 32 Board. As I progress I keep running into stumbling blocks.

Again, thank you for your input.

**Comment by brentru** [comment]
Ah, that repository is super old (and should be archived...). 

Try using one of the sketches included with this library instead, they work V2 of the Adafruit IO API and I fixed a few of them to work with the ESP32: https://github.com/adafruit/Adafruit_IO_Arduino/tree/master/examples

**Comment by brentru** [comment]
Hey @Starkshub: I've brought the[ Adafruit IO + IFTTT Guide](https://learn.adafruit.com/using-ifttt-with-adafruit-io?view=all#arduino-code-2) code section up to date. 

New Code:
https://github.com/adafruit/Adafruit_Learning_System_Guides/tree/master/IFTTT_Door_Detector

Closing...
