### ISSUE TITLE
Removing errors and some warnings from build

### ISSUE THREAD

**Issue by supuflounder** [adafruit/Adafruit_IO_Arduino#48]
- Arduino board:  Feather HUZZAH32 (Adafruit #3405)

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.5

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): Build a project that uses Adafruit IO on a HUZZAH32

Here are the changes I made:
![screen shot 2018-08-01 at 10 54 38 am](https://user-images.githubusercontent.com/11430861/43530562-e6199aec-957b-11e8-861e-f000519e6842.png)
![screen shot 2018-08-01 at 10 54 33 am](https://user-images.githubusercontent.com/11430861/43530563-e62c518c-957b-11e8-811c-572c019d0ee6.png)

**Comment by brentru** [comment]
Thanks @supuflounder! I'm addressing some of these in #52 (the ones specifically regarding Adafruit_IO_Arduino)

**Comment by brentru** [comment]
Addressed the rest of these in https://github.com/adafruit/Adafruit_MQTT_Library/pull/127. Closing...
