### ISSUE TITLE
Confusion, maybe, in config.h

### ISSUE THREAD

**Issue by supuflounder** [adafruit/Adafruit_IO_Arduino#51]
The Feather HUZZAH ESP32 is not mentioned in the comments as being supported by wifi, although I had not seen this omission and am successfully using wifi with my ESP32 (it is able to connect via my wifi to adafruit.io, but then crashes due to other bugs).

**Comment by brentru** [comment]
I added ESP32-compatable examples earlier this summer, didn't see the config.h. I'll update config.h to reflect this change. Thanks!

**Comment by brentru** [comment]
Feather Huzzah32 and product page link has been added `config.h` files, applied globally to `/examples`.

**Comment by supuflounder** [comment]
> Feather Huzzah32 and product page link has been added `config.h` files,
> applied globally to `/examples` in
> https://github.com/adafruit/Adafruit_IO_Arduino/commit/8f4fa471456a47c9209cb3e2e9bb64a8c86b7fb8
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/adafruit/Adafruit_IO_Arduino/issues/51#issuecomment-409972396

Thanks.  Glad I can be a contributor.
       joe
