### ISSUE TITLE
Sketch not compiling after library upgrade

### ISSUE THREAD

**Issue by labomat** [adafruit/Adafruit_IO_Arduino#53]
After updating the library to v 2.7.11 I got multiple compilation errors with my sketch:

> ...\libraries\Adafruit_IO_Arduino\src\blocks\MapBlock.cpp: In member function 'virtual String MapBlock::properties()':
> ... \libraries\Adafruit_IO_Arduino\src\blocks\MapBlock.cpp:26:3: error: expected ')' before '{' token
>    {
>    ^
> ...\libraries\Adafruit_IO_Arduino\src\blocks\MapBlock.cpp:31:3: error: 'props' was not declared in this scope
>    props += historyHours;

Full sketch code: https://github.com/labomat/Pflanzenwaechter/blob/devel/Feuchtesensor_IoT.ino

- Arduino board:  Wemos D1 Mini

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.5

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**

**Comment by brentru** [comment]
Hi @labomat! 2.7.11 should have patched the mapblock problem, I'll look into this.

**Comment by brentru** [comment]
Release 2.7.12 patches this issue. I'm leaving this open until the library manager picks it up and I verify it's patched.

**Comment by labomat** [comment]
The patch removed the first error but not the second.

> ...\libraries\Adafruit_IO_Arduino\src\blocks\MapBlock.cpp:31:3: error: 'props' was not declared in this scope
> props += historyHours;

**Comment by brentru** [comment]
Weird, my compiler didn't register that error until I did an application restart. 

Staging branch for this error: https://github.com/adafruit/Adafruit_IO_Arduino/tree/map-props-patch

**Comment by brentru** [comment]
Ok, patched/pulled in/released. Let me know if you're continuing to have issues.

**Comment by labomat** [comment]
Looks good - thanks for your help!

**Comment by brentru** [comment]
@labomat  Happy to help. 

Closing....
