### ISSUE TITLE
onMessage handler triggering randomly (Gmailbox by Adafruit)

### ISSUE THREAD

**Issue by Ahsan2** [adafruit/Adafruit_IO_Arduino#72]
I followed the "Adafruit IO IFTTT Example - Gmailbox" example of the library. The issue is that my onMessage handler keeps on triggering even if I am not receiving any new feed data. It also triggers properly when I do receive data

**Comment by brentru** [comment]
Can you paste the Serial Monitor output? 

Did you follow the setup on the learn guide (https://learn.adafruit.com/gmailbox/adafruit-io-setup) and have a feed named `gmail`?

**Comment by Ahsan2** [comment]
yes it is a feed named "gmail".
New line gets printed ("You got a new mail") whenever I receive email.
Note that it does work when I receive a proper email, as well as keeps giving false alarms after every few seconds

**Comment by brentru** [comment]
I tested this with the latest Adafruit IO library on an Adafruit Feather Huzzah 8266 and I'm unable to reproduce the error you're having. 

What board are you using?
Which library version are you using?

**Comment by Ahsan2** [comment]
Wemos
Wish I could purchase feather here in my country.
Libraries are all latest. Will give it another try in NodeMCU. Thanks for the response between

**Comment by brentru** [comment]
You're welcome! The Wemos is not a board officially supported by this library. You might have luck using the Adafruit MQTT library (https://github.com/adafruit/Adafruit_MQTT_Library) with Adafruit IO.
