### ISSUE TITLE
Example compiling error: Must define USE_AIRLIFT or USE_WINC1500 before including this file.

### ISSUE THREAD

**Issue by WieFel** [adafruit/Adafruit_IO_Arduino#91]
- Arduino board:  **Adafruit Feather M0**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.9**

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):
I am trying to compile the example **adafruitio_02_pubsub** for my board. I opened the example project using the Arduino IDE.
The only things I modified were the `IO_USERNAME`, `IO_KEY`, `WIFI_SSID` and `WIFI_PASS` fields in the file **config.h**.
In the main file **adafruitio_02_pubsub.ino** I only added the line `WiFi.setPins(8,7,4,2);` as the first line in the `setup()` function as it is done in the setup guide here: https://learn.adafruit.com/adafruit-feather-m0-wifi-atwinc1500/using-the-wifi-module#check-connections-and-version-7-7

However, when compiling the code I get the following error:
```
In file included from sketch/config.h:30:0,
                 from /home/felix/Arduino/adafruitio_02_pubsub/adafruitio_02_pubsub.ino:18:
/home/felix/Arduino/libraries/Adafruit_IO_Arduino/src/AdafruitIO_WiFi.h:47:4: error: #error "Must define USE_AIRLIFT or USE_WINC1500 before including this file."
   #error "Must define USE_AIRLIFT or USE_WINC1500 before including this file."
    ^
exit status 1
Error compiling for board Adafruit Feather M0.
```

I cannot find out what the actual problem is. With earlier versions of the Adafruit IO examples I didn't encounter any problems. All the libraries necessary for using Adafruit board with Arduino IDE (Arduino SAMD Boards, Adafruit SAMD Boards, Adafruit IO Arduino _3.2.0_, WiFi101 _0.16.0_) are uptodate.
Any suggestions?

**Comment by brentru** [comment]
@WieFel  Uncomment  the `#define USE_WINC1500` at the top of your `config.h` file. (see here: https://github.com/adafruit/Adafruit_IO_Arduino/blob/master/examples/adafruitio_02_pubsub/config.h#L27)

Are you using a Feather M0 + a WINC 1500 breakout? 
Or are you using the Adafruit Feather M0 WiFi (integrated Winc1500 module)? 

If you're using the M0 WiFi, you do not need to perform the `WiFi.setPins` call from your `.ino` code, it's added into this library already.

**Comment by WieFel** [comment]
> @WieFel Uncomment the `#define USE_WINC1500` at the top of your `config.h` file. (see here: https://github.com/adafruit/Adafruit_IO_Arduino/blob/master/examples/adafruitio_02_pubsub/config.h#L27)
> 
> Are you using a Feather M0 + a WINC 1500 breakout?
> Or are you using the Adafruit Feather M0 WiFi (integrated Winc1500 module)?
> 
> If you're using the M0 WiFi, you do not need to perform the `WiFi.setPins` call from your `.ino` code, it's added into this library already.

Thanks, uncommenting `#define USE_WINC1500` and removing the `WiFi.setPins` call solved the problem!

**Comment by a7u7a** [comment]
Hi, I'm running into this issue but when I add `#define USE_WINC1500` right after `#include "AdafruitIO_WiFi.h"` then I get the following error: 
```
In file included from /Users/user/Documents/Arduino/libraries/Adafruit_IO_Arduino/src/AdafruitIO_Feed.h:21,
                 from /Users/user/Documents/Arduino/libraries/Adafruit_IO_Arduino/src/AdafruitIO.h:22,
                 from /Users/user/Documents/Arduino/libraries/Adafruit_IO_Arduino/src/wifi/AdafruitIO_WINC1500.h:21,
                 from /Users/user/Documents/Arduino/libraries/Adafruit_IO_Arduino/src/AdafruitIO_WiFi.h:36,
                 from /private/var/folders/mz/mlj68kvx2h3_tsjf6pc5t4500000gn/T/.arduinoIDE-unsaved202326-64261-a6erbb.w0p45/neopixel_and_thermometer/config.h:37,
                 from /private/var/folders/mz/mlj68kvx2h3_tsjf6pc5t4500000gn/T/.arduinoIDE-unsaved202326-64261-a6erbb.w0p45/neopixel_and_thermometer/neopixel_and_thermometer.ino:20:
/Users/user/Documents/Arduino/libraries/Adafruit_MQTT_Library/Adafruit_MQTT.h:28: warning: "strncpy_P" redefined
```

I'm trying to compile the following example from the library: https://github.com/adafruit/Adafruit_IO_Arduino/tree/master/examples/io_home_series/neopixel_and_thermometer

This is on a freshly installed Arduino IDE and latest dependencies

Any pointers on how to compile this?
